#!/usr/bin/env python3
"""
Podcast Transcriber for UHN Accessibility First Course Series
Transcribes podcast audio to timestamped text, SRT captions, and a cut guide.

Uses OpenAI Whisper API (requires OPENAI_API_KEY) for accurate timestamps.

Usage:
    python transcribe_podcast.py                              # Transcribe default podcast
    python transcribe_podcast.py --file path/to/audio.m4a     # Transcribe specific file
    python transcribe_podcast.py --both                       # Transcribe both podcasts

Requirements:
    pip install openai python-dotenv
    OPENAI_API_KEY must be set in environment or .env file
"""

import argparse
import json
import os
import sys
from pathlib import Path

try:
    from openai import OpenAI
except ImportError:
    print("Error: openai package not installed. Run: pip install openai")
    sys.exit(1)

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PODCAST_DIR = BASE_DIR / "05-build-output" / "01-Foundations-of-Disability-Inclusion-and-Accessible-Design" / "08-notebooklm-podcast"

DEFAULT_FILES = [
    PODCAST_DIR / "Five_words_to_restore_patient_dignity.m4a",
    PODCAST_DIR / "Hospital_Accessibility_Beyond_Ramps_and_Concrete.m4a",
]


def format_time_srt(seconds: float) -> str:
    """Convert seconds to SRT timestamp format HH:MM:SS,mmm."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds % 1) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def format_time_short(seconds: float) -> str:
    """Convert seconds to MM:SS."""
    m = int(seconds // 60)
    s = int(seconds % 60)
    return f"{m}:{s:02d}"


def transcribe_with_openai(file_path: Path, api_key: str) -> dict:
    """Transcribe using OpenAI Whisper API with word-level timestamps."""
    client = OpenAI(api_key=api_key)

    print(f"  Uploading to OpenAI Whisper API...")
    print(f"  File: {file_path.name} ({file_path.stat().st_size / 1024 / 1024:.1f} MB)")

    with open(file_path, "rb") as f:
        # Use verbose_json to get segment-level timestamps
        response = client.audio.transcriptions.create(
            model="whisper-1",
            file=f,
            response_format="verbose_json",
            timestamp_granularities=["segment"],
            language="en",
        )

    return response


def save_transcript(segments: list, output_path: Path, source_name: str):
    """Save full transcript as markdown with timestamps."""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# Transcript — {source_name}\n\n")
        f.write(f"**Source:** `{source_name}`\n")
        f.write(f"**Generated by:** OpenAI Whisper API\n")
        f.write(f"**Date:** {__import__('time').strftime('%Y-%m-%d')}\n\n")
        f.write("---\n\n")

        for seg in segments:
            start = seg.get("start", 0)
            end = seg.get("end", 0)
            text = seg.get("text", "").strip()
            f.write(f"**[{format_time_short(start)}]** {text}\n\n")

        # Summary
        if segments:
            total_duration = segments[-1].get("end", 0)
            f.write("---\n\n")
            f.write(f"**Total Duration:** {format_time_short(total_duration)}\n")
            f.write(f"**Total Segments:** {len(segments)}\n")

    print(f"  ✓ Transcript: {output_path.name}")


def save_srt(segments: list, output_path: Path):
    """Save SRT caption file."""
    with open(output_path, "w", encoding="utf-8") as f:
        for i, seg in enumerate(segments, 1):
            start = seg.get("start", 0)
            end = seg.get("end", 0)
            text = seg.get("text", "").strip()
            f.write(f"{i}\n")
            f.write(f"{format_time_srt(start)} --> {format_time_srt(end)}\n")
            f.write(f"{text}\n\n")

    print(f"  ✓ Captions: {output_path.name}")


def save_cut_guide(segments: list, output_path: Path, source_name: str):
    """Save a cut guide showing topic flow with timestamps for easy segment selection."""
    # Group segments into ~30 second chunks for easier scanning
    chunks = []
    current_chunk = {"start": 0, "texts": [], "end": 0}

    for seg in segments:
        start = seg.get("start", 0)
        end = seg.get("end", 0)
        text = seg.get("text", "").strip()

        if start - current_chunk["start"] > 30 and current_chunk["texts"]:
            current_chunk["end"] = start
            chunks.append(current_chunk)
            current_chunk = {"start": start, "texts": [], "end": 0}

        current_chunk["texts"].append(text)
        current_chunk["end"] = end

    if current_chunk["texts"]:
        chunks.append(current_chunk)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(f"# Cut Guide — {source_name}\n\n")
        f.write("Use this guide to identify the best segments to keep.\n")
        f.write("Mark segments with ✓ to keep, ✗ to cut.\n\n")
        f.write("## Segment-by-Segment Flow\n\n")
        f.write("| # | Time | Duration | Content Preview | Keep? |\n")
        f.write("|---|------|----------|-----------------|-------|\n")

        for i, chunk in enumerate(chunks, 1):
            start = format_time_short(chunk["start"])
            end = format_time_short(chunk["end"])
            dur = chunk["end"] - chunk["start"]
            preview = " ".join(chunk["texts"])[:100] + "..."
            f.write(f"| {i} | {start}–{end} | {format_time_short(dur)} | {preview} | |\n")

        f.write("\n\n## How to Use\n\n")
        f.write("1. Review each segment's content preview\n")
        f.write("2. Mark which segments to keep (target ~5 minutes total)\n")
        f.write("3. Run the cut script:\n")
        f.write("   ```\n")
        f.write(f'   python cut_podcast.py --segments "START-END,START-END"\n')
        f.write("   ```\n")
        f.write(f"\n**Source topics to look for:**\n")
        f.write("- The intake moment / first 30 seconds\n")
        f.write("- The five words: \"What works best for you?\"\n")
        f.write("- The confirmation: \"Did I get that right?\"\n")
        f.write("- One sentence for a busy shift\n")
        f.write("- \"Dignity starts before the appointment\"\n")

    print(f"  ✓ Cut guide: {output_path.name}")


def save_json(response_data: dict, output_path: Path):
    """Save raw API response as JSON for reference."""
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(response_data, f, indent=2, default=str)
    print(f"  ✓ Raw JSON: {output_path.name}")


def transcribe_file(file_path: Path, api_key: str):
    """Transcribe a single file and save all outputs."""
    stem = file_path.stem

    print(f"\n{'=' * 60}")
    print(f"  Transcribing: {file_path.name}")
    print(f"{'=' * 60}\n")

    # Transcribe
    response = transcribe_with_openai(file_path, api_key)

    # Extract segments
    segments = []
    if hasattr(response, 'segments') and response.segments:
        segments = [{"start": s.start, "end": s.end, "text": s.text} for s in response.segments]
    elif hasattr(response, 'text'):
        # Fallback: no segments, just full text
        segments = [{"start": 0, "end": 0, "text": response.text}]

    if not segments:
        print("  Warning: No segments returned. Saving full text only.")
        segments = [{"start": 0, "end": 0, "text": getattr(response, 'text', 'No text')}]

    # Save outputs
    output_dir = file_path.parent
    save_transcript(segments, output_dir / f"{stem}_transcript.md", file_path.name)
    save_srt(segments, output_dir / f"{stem}.srt")
    save_cut_guide(segments, output_dir / f"{stem}_cut_guide.md", file_path.name)
    save_json({"text": getattr(response, 'text', ''), "segments": segments},
              output_dir / f"{stem}_whisper.json")

    # Print summary
    total_dur = segments[-1]["end"] if segments else 0
    print(f"\n  Total duration: {format_time_short(total_dur)}")
    print(f"  Total segments: {len(segments)}")
    print(f"  Full text length: {len(getattr(response, 'text', ''))} chars")


def main():
    parser = argparse.ArgumentParser(description="Transcribe podcast audio for UHN Accessibility First")
    parser.add_argument("--file", type=str, default=None, help="Path to audio file")
    parser.add_argument("--both", action="store_true", help="Transcribe both default podcast files")
    parser.add_argument("--api-key", type=str, default=None, help="OpenAI API key (or set OPENAI_API_KEY env var)")
    args = parser.parse_args()

    api_key = args.api_key or os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("Error: OPENAI_API_KEY not set.")
        print("  Set it with: export OPENAI_API_KEY='sk-...'")
        print("  Or pass --api-key 'sk-...'")
        sys.exit(1)

    if args.file:
        file_path = Path(args.file)
        if not file_path.exists():
            print(f"Error: File not found: {file_path}")
            sys.exit(1)
        transcribe_file(file_path, api_key)
    elif args.both:
        for f in DEFAULT_FILES:
            if f.exists():
                transcribe_file(f, api_key)
            else:
                print(f"Skipping (not found): {f.name}")
    else:
        # Default: transcribe the "Five words" podcast
        if DEFAULT_FILES[0].exists():
            transcribe_file(DEFAULT_FILES[0], api_key)
        else:
            print(f"Error: Default file not found: {DEFAULT_FILES[0]}")
            print("Available files:")
            for f in PODCAST_DIR.glob("*.m4a"):
                print(f"  {f.name}")
            sys.exit(1)


if __name__ == "__main__":
    main()
